# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K9sRca < Formula
  desc "K9s plugin for Komodor Root Cause Analysis"
  homepage "https://github.com/komodorio/k9s-rca"
  version "1.0.0"
  license "MIT"

  depends_on "k9s" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/komodorio/k9s-rca/releases/download/v1.0.0/k9s-rca-1.0.0-darwin-amd64.tar.gz"
      sha256 "715b183def9ecaf3a9b35fe928a6c9e3a9b1ad3ba658fa8fafd66bf562ad47b3"

      def install
        bin.install "k9s-rca"
        (buildpath/"k9s_rca_plugin.yaml").write <<~EOS
          # K9s RCA Plugin Configuration
          #
          # PREREQUISITES (required - can be set via env vars or -- flags):
          # export KOMODOR_API_KEY="your-komodor-api-token"
          #
          # USAGE: Press Shift-K while viewing any supported Kubernetes resource
          #
          plugins:
            rca-resource:
              shortCut: Shift-K
              description: "Komodor RCA"
              scopes:
              - po
              - deploy
              - svc
              - sts
              - ds
              - ing
              - cm
              - sec
              - pvc
              - job
              - cj
              - rs
              - hpa
              - pdb
              - np
              command: k9s-rca
              background: false
              args:
              - --kind=$RESOURCE_NAME
              - --namespace=$NAMESPACE
              - --name=$NAME
              - --cluster=$CLUSTER
              - --context=$CONTEXT
              - --poll
        EOS
        pkgshare.install "k9s_rca_plugin.yaml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/komodorio/k9s-rca/releases/download/v1.0.0/k9s-rca-1.0.0-darwin-arm64.tar.gz"
      sha256 "b8b7ff9675029773d1393a5ae16083dd69877f92c36086e3f81ea9b76d06825e"

      def install
        bin.install "k9s-rca"
        (buildpath/"k9s_rca_plugin.yaml").write <<~EOS
          # K9s RCA Plugin Configuration
          #
          # PREREQUISITES (required - can be set via env vars or -- flags):
          # export KOMODOR_API_KEY="your-komodor-api-token"
          #
          # USAGE: Press Shift-K while viewing any supported Kubernetes resource
          #
          plugins:
            rca-resource:
              shortCut: Shift-K
              description: "Komodor RCA"
              scopes:
              - po
              - deploy
              - svc
              - sts
              - ds
              - ing
              - cm
              - sec
              - pvc
              - job
              - cj
              - rs
              - hpa
              - pdb
              - np
              command: k9s-rca
              background: false
              args:
              - --kind=$RESOURCE_NAME
              - --namespace=$NAMESPACE
              - --name=$NAME
              - --cluster=$CLUSTER
              - --context=$CONTEXT
              - --poll
        EOS
        pkgshare.install "k9s_rca_plugin.yaml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/komodorio/k9s-rca/releases/download/v1.0.0/k9s-rca-1.0.0-linux-amd64.tar.gz"
      sha256 "65504013a3d0ae121740cc6a8c6ed7d499eeee3887de6e94a374f5db63c83191"
      def install
        bin.install "k9s-rca"
        (buildpath/"k9s_rca_plugin.yaml").write <<~EOS
          # K9s RCA Plugin Configuration
          #
          # PREREQUISITES (required - can be set via env vars or -- flags):
          # export KOMODOR_API_KEY="your-komodor-api-token"
          #
          # USAGE: Press Shift-K while viewing any supported Kubernetes resource
          #
          plugins:
            rca-resource:
              shortCut: Shift-K
              description: "Komodor RCA"
              scopes:
              - po
              - deploy
              - svc
              - sts
              - ds
              - ing
              - cm
              - sec
              - pvc
              - job
              - cj
              - rs
              - hpa
              - pdb
              - np
              command: k9s-rca
              background: false
              args:
              - --kind=$RESOURCE_NAME
              - --namespace=$NAMESPACE
              - --name=$NAME
              - --cluster=$CLUSTER
              - --context=$CONTEXT
              - --poll
        EOS
        pkgshare.install "k9s_rca_plugin.yaml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/komodorio/k9s-rca/releases/download/v1.0.0/k9s-rca-1.0.0-linux-arm64.tar.gz"
      sha256 "58496f63ef4279995e2fcbab8b2f01f34c15512da266d74ae8ee429a2f3a6ff6"
      def install
        bin.install "k9s-rca"
        (buildpath/"k9s_rca_plugin.yaml").write <<~EOS
          # K9s RCA Plugin Configuration
          #
          # PREREQUISITES (required - can be set via env vars or -- flags):
          # export KOMODOR_API_KEY="your-komodor-api-token"
          #
          # USAGE: Press Shift-K while viewing any supported Kubernetes resource
          #
          plugins:
            rca-resource:
              shortCut: Shift-K
              description: "Komodor RCA"
              scopes:
              - po
              - deploy
              - svc
              - sts
              - ds
              - ing
              - cm
              - sec
              - pvc
              - job
              - cj
              - rs
              - hpa
              - pdb
              - np
              command: k9s-rca
              background: false
              args:
              - --kind=$RESOURCE_NAME
              - --namespace=$NAMESPACE
              - --name=$NAME
              - --cluster=$CLUSTER
              - --context=$CONTEXT
              - --poll
        EOS
        pkgshare.install "k9s_rca_plugin.yaml"
      end
    end
  end

  def caveats
    <<~EOS
      To use this plugin with k9s:

      1. Set your Komodor API key:
         export KOMODOR_API_KEY="your-api-key"

      2. Copy the plugin configuration to k9s:
         mkdir -p ~/.config/k9s
         cp #{pkgshare}/k9s_rca_plugin.yaml ~/.config/k9s/plugins.yaml

      3. Start k9s and press Shift-K on any supported resource to trigger RCA

      For more information, visit: https://github.com/komodorio/k9s-rca
    EOS
  end
end
